export type Parent = {
    [key: number]: string;
};

export const fatherList: Parent = {
    [0]: 'Benjamin',
    [1]: 'Daniel',
    [2]: 'Joshua',
    [3]: 'Noah',
    [4]: 'Andrew',
    [5]: 'Joan',
    [6]: 'Alex',
    [7]: 'Isaac',
    [8]: 'Evan',
    [9]: 'Ethan',
    [10]: 'Vincent',
    [11]: 'Angel',
    [12]: 'Diego',
    [13]: 'Adrian',
    [14]: 'Gabriel',
    [15]: 'Michael',
    [16]: 'Santiago',
    [17]: 'Kevin',
    [18]: 'Louis',
    [19]: 'Samuel',
    [20]: 'Anthony',
    [42]: 'Claude',
    [43]: 'Niko',
    [44]: 'John',
};

export const motherList: Parent = {
    [21]: 'Hannah',
    [22]: 'Audrey',
    [23]: 'Jasmine',
    [24]: 'Giselle',
    [25]: 'Amelia',
    [26]: 'Isabella',
    [27]: 'Zoe',
    [28]: 'Ava',
    [29]: 'Camilla',
    [30]: 'Violet',
    [31]: 'Sophia',
    [32]: 'Eveline',
    [33]: 'Nicole',
    [34]: 'Ashley',
    [35]: 'Grace',
    [36]: 'Brianna',
    [37]: 'Natalie',
    [38]: 'Olivia',
    [39]: 'Elizabeth',
    [40]: 'Charlotte',
    [41]: 'Emma',
    [45]: 'Misty',
};